### ISSUE TITLE
Results navigation broken

### ISSUE THREAD

**Issue by Atoboldom** [rkucsora/ecosia-keyboard-shortcuts#2]
Hello !

For the past few days, pressing the J and K keys no longer selects search results.
Also the blue frame no longer appears.

I was able to fix the issue by replacing the selector used in code by one I found in the Ecosia result page.
Ecosia may have changed the result selectors recently.

Fixed in ecosia_keyboard_shortcuts.js:6:
```
-const results = document.querySelectorAll(".card-web .result");
+const results = document.querySelectorAll(".layout-card");
```

**Comment by rkucsora** [comment]
Hi

Thanks for bug report and the patch.

The original code still works for me. Perhaps Ecosia is rolling out a new layout to the users incrementally. I will release a new version with combining the two selectors.
